image: mhart/alpine-node:12.18

stages:
  - install&build
  - deploy

install&build:
  stage: install&build
  script:
    - npm install
    - npm run build
    - mv dist/ public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
      - public
  dependencies:
    - install&build
  only:
  - master
